### ISSUE TITLE
No content displayed in https://wordpress.org/gutenberg/ page

### ISSUE THREAD

**Issue by marcarmengou** [WordPress/wporg-gutenberg#60] opened 2023-07-27 10:11 UTC
**Describe the bug**
No content displayed in https://wordpress.org/gutenberg/ page. 

Visit https://wordpress.org/ scroll down to "Dream it, build it" and click on the link "[Explore the WordPress Editor ↗︎](https://wordpress.org/gutenberg/)"

**To Reproduce**
1. Go to '[WordPress.org.](https://wordpress.org/)'
2. Click on '[Explore the WordPress Editor ↗︎](https://wordpress.org/gutenberg/)'

**Expected behavior**
The content of the page should appear https://wordpress.org/gutenberg/

**Screenshots**
![gutenberg-link](https://github.com/WordPress/wporg-main-2022/assets/83702259/a71a8158-0d9f-481d-a854-9fe15571f75d)

**Desktop:**
 - OS: [Windows 10]
 - Browser [Chrome 114 and Firefox 115]

**Comment by peteringersoll** [comment] 2023-07-27 13:18
Similarly, About -> Gutenberg goes to the same currently blank page. The page source is there; it's just not rendering. Also note that the link dropped a user right into the editor with no explanation rather than explaining how the editor works and then a "try it" -type link.

**Comment by ryelle** [comment] 2023-07-27 15:47
I've moved this from the wporg-main-2022 repo because the link on the homepage is technically correct, but the issue is with the /gutenberg/ page. It's just showing an empty grey screen:

![](https://github.com/WordPress/wporg-gutenberg/assets/541093/0e80e90e-ff66-487b-8134-92bc5ce12525)

No console errors, just not loading.

**Comment by dd32** [comment] 2023-07-28 03:30
Per https://wordpress.slack.com/archives/C02QB8GMM/p1690435021175989 this is related to something changing in Gutenberg 16.3, as it works with 16.2.1.

I wasn't able to immediately figure out why, I believe someone closer to Gutenberg development will likely need to take a look.. 

My guess is that something in the `wp.editPost.initializeEditor()` call has changed.

Followed up in <A href="https://wordpress.slack.com/archives/C02QB2JS7/p1690515099156599">#core-editor</a> to see if anyone has any pointers.

**Comment by dd32** [comment] 2023-07-28 05:29
Looks like this was resolved via https://github.com/WordPress/wporg-gutenberg/commit/3fa16aa67d4f3ff479d4cf9b7d690f7e7172e285

**Closed as completed by dd32** 2023-07-28 05:29 UTC
